### PR TITLE
Fixed mentioned issues

### LINKED ISSUE #1: In Routes Folder
Add router.route('/') and then add the request methods instead of adding each req method alone

### LINKED ISSUE #2: in app.js
You should add the dotenv at the very top
express.static() just use the name of the folder "public" not "./public"

### PR DESCRIPTION
**Pull request by gittakisnani**
I have fixed the two mentioned issues:

- Added the router.route() in the routes.js file
- Edited some status codes
- Edited the type of keys in the Task Model
- Switched dotenv.config to the very top of the app.js

### CODE REVIEW

File: routes/tasks.js [hunk 1]
```diff
@@ -2,10 +2,13 @@ const express = require("express");
...
-router.patch("/:id", updateTask);
-router.delete("/:id", deleteTask);
+router.route('/')
+    .get(getAllTasks)
+    .post(createTask)
+
+router.route('/:id')
+    .get(getSingleTask)
+    .patch(updateTask)
+    .delete(deleteTask)
```
Comment (yuktnk) [inline routes/tasks.js:12]: good 👍

**Review by yuktnk — APPROVED** [review]
Thanks for letting me know! 😍
